build_from:
  aarch64: "homeassistant/aarch64-base-python:3.9-alpine3.13"
  amd64: "homeassistant/amd64-base-python:3.9-alpine3.13"
  armhf: "homeassistant/armhf-base-python:3.9-alpine3.13"
  armv7: "homeassistant/armv7-base-python:3.9-alpine3.13"
  i386: "homeassistant/i386-base-python:3.9-alpine3.13"
args:
  TEMPIO_VERSION: "2021.09.0"
  S6_OVERLAY_VERSION: "v3.1.2.1"
